export const BUSINESS_ADD_ORG_REQUEST = "BUSINESS_ADD_ORG_REQUEST";
export const BUSINESS_ADD_ORG_SUCCESS = "BUSINESS_ADD_ORG_SUCCESS";
export const BUSINESS_ADD_ORG_FAILURE = "BUSINESS_ADD_ORG_FAILURE";

export const BUSINESS_ADD_STUDENT_REQUEST = "BUSINESS_REGISTER_REQUEST";
export const BUSINESS_ADD_STUDENT_SUCCESS = "BUSINESS_REGISTER_SUCCESS";
export const BUSINESS_ADD_STUDENT_FAILURE = "BUSINESS_REGISTER_FAILURE";

export const BUSINESS_ADD_INSTRUCTOR_REQUEST = "BUSINESS_REGISTER_REQUEST";
export const BUSINESS_ADD_INSTRUCTOR_SUCCESS = "BUSINESS_REGISTER_SUCCESS";
export const BUSINESS_ADD_INSTRUCTOR_FAILURE = "BUSINESS_REGISTER_FAILURE";
