import axios from "axios";

import { 
    BUSINESS_ADD_ORG_REQUEST, 
    BUSINESS_ADD_ORG_SUCCESS,
    BUSINESS_ADD_ORG_FAILURE,
    BUSINESS_ADD_INSTRUCTOR_REQUEST,
    BUSINESS_ADD_INSTRUCTOR_SUCCESS,
    BUSINESS_ADD_INSTRUCTOR_FAILURE,
    BUSINESS_ADD_STUDENT_REQUEST,
    BUSINESS_ADD_STUDENT_SUCCESS,
    BUSINESS_ADD_STUDENT_FAILURE
} from "constants/business/addUsersConstants";
